import type { Posting, ScanStep } from "./types";

export const POSTINGS: Posting[] = [
  {
    id: "orbit-fe-2026",
    url: "https://orbit.work/careers/senior-frontend-2026",
    company: "Orbit",
    role: "Senior Frontend Engineer",
    location: "Remote · Worldwide",
    compMin: 165000,
    compMax: 215000,
    equity: "0.05 – 0.15%",
    posted: "4 days ago",
    summary:
      "Build the inspection canvas for a developer-tools product used by 18,000 engineers. Ship to production weekly. Set the bar for craft on a four-person frontend team.",
    score: 94,
    verdict: "VERIFIED",
    headline: "A clean signal, end to end.",
    editorial:
      "Orbit looks like a real opportunity. The company is registered, the recruiter is identifiable, the posting has been live for four days with no telltale recycling, and the offer’s scope-to-compensation ratio sits comfortably above the 60th percentile for senior frontend roles. We found no red flags. The four-person engineering team has been public on GitHub for 22 months — long enough to verify, short enough to be interesting.",
    pillars: [
      {
        name: "Real",
        score: 96,
        verdict: "pass",
        summary: "Company, domain, and recruiter all check out across independent sources.",
        evidence: [
          { weight: "strong", text: "Domain orbit.work registered 2022‑03‑11, NS records stable for 38 months.", src: "whois.iana.org" },
          { weight: "strong", text: "Delaware C‑corp filing on record. EIN matches Stripe Atlas issuance.", src: "sec.gov/edgar" },
          { weight: "strong", text: "Recruiter Maya Chen — LinkedIn tenure 19 months, two prior verified roles at Vercel.", src: "linkedin.com" },
          { weight: "weak", text: "Role copy contains specifics absent from any other live posting (98.4% novelty).", src: "lighthouse/diff" },
        ],
      },
      {
        name: "Active",
        score: 91,
        verdict: "pass",
        summary: "Posting is fresh and the team is hiring — not warehousing resumes.",
        evidence: [
          { weight: "strong", text: "First seen 2026‑05‑17. No prior version in archive.org snapshots.", src: "web.archive.org" },
          { weight: "strong", text: "Average response time on Hacker News “Who is hiring” threads: 2.3 days.", src: "news.ycombinator.com" },
          { weight: "medium", text: "Two engineers joined the team within the last quarter, per LinkedIn employment.", src: "linkedin.com" },
          { weight: "weak", text: "Careers page last‑modified header within 12 hours of crawl.", src: "http/headers" },
        ],
      },
      {
        name: "Fair",
        score: 93,
        verdict: "pass",
        summary: "Compensation, equity, and scope are coherent for a senior IC role.",
        evidence: [
          { weight: "strong", text: "Cash band $165k–$215k sits at p62–p84 of Levels.fyi senior frontend, US‑remote.", src: "levels.fyi" },
          { weight: "strong", text: "Equity 0.05‑0.15% at Series A is within Carta’s 25‑75th band for the stage.", src: "carta.com" },
          { weight: "medium", text: "Scope statement names a single product surface — not a multi‑disciplinary catch‑all.", src: "lighthouse/scope" },
          { weight: "medium", text: "No mandatory unpaid trial task; paid take‑home capped at 4 hours.", src: "posting" },
        ],
      },
      {
        name: "Credible",
        score: 95,
        verdict: "pass",
        summary: "Small team with verifiable history and an actually‑shipped product.",
        evidence: [
          { weight: "strong", text: "Founders: 2 ex‑Linear, 1 ex‑Figma. Each LinkedIn profile predates Orbit by 6+ years.", src: "linkedin.com" },
          { weight: "strong", text: "Public product at orbit.work — sign‑up flow works, billing live via Stripe.", src: "lighthouse/crawl" },
          { weight: "medium", text: "$4.2M seed led by South Park Commons, Apr 2024. Co‑investors named.", src: "crunchbase.com" },
          { weight: "medium", text: "47 GitHub repositories under orbit‑labs, 11 with commits in the last 14 days.", src: "github.com" },
        ],
      },
    ],
    activity: {
      reposts: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
      label: "Single posting, 12 days online",
      responseDays: 2.3,
      ghostScore: 0.04,
    },
    comparables: [
      { co: "Linear", role: "Senior Frontend Engineer", comp: "$180k–$220k", score: 92 },
      { co: "Vercel", role: "Frontend Engineer, Dashboard", comp: "$170k–$210k", score: 89 },
      { co: "Raycast", role: "Senior Engineer, Web", comp: "$160k–$200k", score: 90 },
    ],
  },
  {
    id: "beacon-pd-2026",
    url: "https://beaconlabs.io/jobs/product-designer",
    company: "Beacon Labs",
    role: "Product Designer",
    location: "Remote · Americas",
    compMin: 95000,
    compMax: 115000,
    equity: "undisclosed",
    posted: "11 weeks ago",
    summary:
      "Own design end-to-end across web and mobile. Work directly with the founder on a generative-AI productivity suite. Move fast.",
    score: 62,
    verdict: "INVESTIGATE",
    headline: "Real company. Stale posting. Vague offer.",
    editorial:
      "Beacon Labs exists, the team is identifiable, and the product appears to function. But the posting itself raises questions: it has been live for eleven weeks across at least three boards with no copy revision, the equity field is blank, and the role bundles three jobs into one — which usually signals either an unclear plan or an under‑scoped budget. We recommend a 20‑minute conversation with the hiring manager before sending a portfolio.",
    pillars: [
      {
        name: "Real",
        score: 88,
        verdict: "pass",
        summary: "Company is real and identifiable. No impersonation patterns detected.",
        evidence: [
          { weight: "strong", text: "Domain beaconlabs.io registered 2023‑06‑02. WHOIS contact matches founder.", src: "whois.iana.org" },
          { weight: "strong", text: "Delaware C‑corp filed Aug 2023. Active in good standing.", src: "sec.gov/edgar" },
          { weight: "medium", text: "Recruiter posting on LinkedIn — 8‑month tenure, prior career visible.", src: "linkedin.com" },
          { weight: "weak", text: "Posting copy not found verbatim on any other domain.", src: "lighthouse/diff" },
        ],
      },
      {
        name: "Active",
        score: 38,
        verdict: "fail",
        summary: "Long‑running listing with multiple identical reposts. Likely warehousing resumes.",
        evidence: [
          { weight: "strong", text: "First seen 2026‑03‑03 — 79 days ago. Re‑posted 4 times without copy changes.", src: "web.archive.org" },
          { weight: "strong", text: "Listed simultaneously on LinkedIn, Wellfound, and Otta. Same headline, same body.", src: "lighthouse/crawl" },
          { weight: "medium", text: "14 Reddit users in r/UXDesign report no response after applying.", src: "reddit.com" },
          { weight: "medium", text: "Careers page modified once in 79 days — same posting, no removals.", src: "http/headers" },
        ],
      },
      {
        name: "Fair",
        score: 51,
        verdict: "fail",
        summary: "Compensation below market for the scope described. Equity undisclosed.",
        evidence: [
          { weight: "strong", text: "Cash band $95k–$115k sits at p18–p32 for senior product design, US‑remote.", src: "levels.fyi" },
          { weight: "strong", text: "Role bundles design + research + light frontend. Three jobs, one salary.", src: "lighthouse/scope" },
          { weight: "medium", text: "Equity field left blank. Best Companies for Equity reports median 0.10% at this stage.", src: "carta.com" },
          { weight: "weak", text: "Unpaid 5‑day design exercise mentioned in step 3 of the process.", src: "posting" },
        ],
      },
      {
        name: "Credible",
        score: 72,
        verdict: "mixed",
        summary: "Product ships, but signals around the team are thin.",
        evidence: [
          { weight: "medium", text: "Public product at beaconlabs.io. Sign‑up works; pricing page partially complete.", src: "lighthouse/crawl" },
          { weight: "medium", text: "Founder LinkedIn predates company by 3 years. One prior exit (acqui‑hire).", src: "linkedin.com" },
          { weight: "weak", text: "No funding announced. Self‑funded according to founder’s tweet from Feb 2026.", src: "x.com" },
          { weight: "weak", text: "4 employees on LinkedIn. Last hire 9 months ago.", src: "linkedin.com" },
        ],
      },
    ],
    activity: {
      reposts: [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1],
      label: "Reposted 4 times in 79 days, copy unchanged",
      responseDays: 14,
      ghostScore: 0.62,
    },
    comparables: [
      { co: "Linear", role: "Product Designer", comp: "$160k–$200k", score: 90 },
      { co: "Arc", role: "Senior Product Designer", comp: "$140k–$180k", score: 86 },
      { co: "Replit", role: "Product Designer, Mobile", comp: "$155k–$195k", score: 88 },
    ],
  },
  {
    id: "globalreach-mkt-2026",
    url: "https://globalreach-solutions.work/careers/marketing-coordinator",
    company: "GlobalReach Solutions",
    role: "Marketing Coordinator (Remote)",
    location: "Anywhere · Flexible hours",
    compMin: 7800,
    compMax: 9500,
    equity: "—",
    posted: "today",
    summary:
      "Earn $7,800 – $9,500/month working from home! No experience required. Flexible schedule. Immediate start. Help us expand into your region.",
    score: 18,
    verdict: "DECLINE",
    headline: "Eleven independent red flags. Do not apply.",
    editorial:
      "This is almost certainly fraudulent. The domain was registered fourteen days ago, the company name appears nowhere outside this single posting and a clone of it, the recruiter’s contact is a Gmail address, and the compensation is decoupled from any plausible scope of work. We have logged it for the FTC consumer‑complaint database. If you have already corresponded, do not send identification, banking details, or pay for any “equipment” or “training.”",
    pillars: [
      {
        name: "Real",
        score: 14,
        verdict: "fail",
        summary: "Almost every identity signal fails. Likely impersonation or shell entity.",
        evidence: [
          { weight: "strong", text: "Domain registered 2026‑05‑07 — 14 days ago. Privacy‑masked registrant.", src: "whois.iana.org" },
          { weight: "strong", text: "No corporate registration found in DE, CA, DE, NY, UK, or IE registries.", src: "sec.gov/edgar" },
          { weight: "strong", text: "Recruiter contact: hr.globalreach@gmail.com — not on company domain.", src: "posting" },
          { weight: "strong", text: "Company name returns 0 hits on Google with quotes plus location. Listing is the only source.", src: "google.com" },
        ],
      },
      {
        name: "Active",
        score: 22,
        verdict: "fail",
        summary: "Posted today, but identical copy already lives at three sibling domains.",
        evidence: [
          { weight: "strong", text: "Identical body text found at globalreach‑careers.net and gr‑remote.work.", src: "lighthouse/diff" },
          { weight: "strong", text: "4 BBB scam reports filed against the phrase “GlobalReach Solutions” this quarter.", src: "bbb.org" },
          { weight: "medium", text: "r/Scams thread from 4 days ago reports the same posting and contact email.", src: "reddit.com" },
          { weight: "weak", text: "No careers infrastructure — page is a single static HTML file, no ATS.", src: "lighthouse/crawl" },
        ],
      },
      {
        name: "Fair",
        score: 9,
        verdict: "fail",
        summary: "Pay‑to‑scope ratio is implausible. Hits 7 of 9 textbook scam markers.",
        evidence: [
          { weight: "strong", text: "$94k–$114k for entry‑level marketing with no qualifications: p99.4 outlier.", src: "levels.fyi" },
          { weight: "strong", text: "\"Flexible hours, immediate start, no experience\" — three of the FTC’s named scam patterns.", src: "ftc.gov" },
          { weight: "strong", text: "Posting requests a copy of government ID before interview.", src: "posting" },
          { weight: "strong", text: "Process mentions a $189 “training materials” purchase, reimbursed after 30 days.", src: "posting" },
        ],
      },
      {
        name: "Credible",
        score: 26,
        verdict: "fail",
        summary: "No verifiable product, team, history, or funding. Nothing checks out.",
        evidence: [
          { weight: "strong", text: "Site has no product, no blog, no team page. Just the one job posting.", src: "lighthouse/crawl" },
          { weight: "strong", text: "0 LinkedIn employees. 0 GitHub presence. 0 press mentions.", src: "linkedin.com" },
          { weight: "strong", text: "Stock photo on “About” page reverse‑searches to a 2014 Shutterstock asset.", src: "tineye.com" },
          { weight: "medium", text: "Domain is the 47th .work TLD registration by this anonymized owner in 2026.", src: "whois.iana.org" },
        ],
      },
    ],
    activity: {
      reposts: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
      label: "Copy duplicated across 3 known scam domains",
      responseDays: null,
      ghostScore: 0.94,
    },
    comparables: [
      { co: "Buffer", role: "Marketing Coordinator", comp: "$72k–$88k", score: 91 },
      { co: "Webflow", role: "Marketing Associate", comp: "$78k–$95k", score: 88 },
      { co: "Ghost", role: "Marketing Coordinator", comp: "$65k–$82k", score: 87 },
    ],
  },
];

export const SCAN_STEPS: ScanStep[] = [
  { pillar: "Real", check: "Resolving domain WHOIS · whois.iana.org" },
  { pillar: "Real", check: "Cross-referencing SEC EDGAR registrant" },
  { pillar: "Real", check: "Matching recruiter LinkedIn footprint" },
  { pillar: "Real", check: "Computing posting-copy novelty score" },
  { pillar: "Active", check: "Pulling archive.org snapshot history" },
  { pillar: "Active", check: "Diffing repost copy across 14 boards" },
  { pillar: "Active", check: "Sampling Reddit / Blind response signals" },
  { pillar: "Active", check: "Inspecting careers-page Last-Modified header" },
  { pillar: "Fair", check: "Querying Levels.fyi percentile bands" },
  { pillar: "Fair", check: "Cross-referencing Carta equity benchmarks" },
  { pillar: "Fair", check: "Scoring scope-to-comp ratio" },
  { pillar: "Fair", check: "Detecting unpaid-trial language" },
  { pillar: "Credible", check: "Mapping founder employment history" },
  { pillar: "Credible", check: "Verifying live product surface" },
  { pillar: "Credible", check: "Reconciling funding via Crunchbase" },
  { pillar: "Credible", check: "Counting GitHub commits, last 30 days" },
];

export const LIBRARY_EXTRA = [
  { id: "x-1", company: "Mercury", role: "Engineering Manager, Payments", score: 88, verdict: "VERIFIED" as const, posted: "2d", source: "mercury.com" },
  { id: "x-2", company: "Sourcegraph", role: "Staff Engineer, Cody", score: 91, verdict: "VERIFIED" as const, posted: "5d", source: "sourcegraph.com" },
  { id: "x-3", company: "NorthDigital LLC", role: "Customer Success Mgr.", score: 41, verdict: "INVESTIGATE" as const, posted: "8w", source: "linkedin.com" },
  { id: "x-4", company: "Apexa Group", role: "Remote Data Entry", score: 12, verdict: "DECLINE" as const, posted: "1d", source: "indeed.com" },
  { id: "x-5", company: "Replicate", role: "Senior Backend Engineer", score: 90, verdict: "VERIFIED" as const, posted: "3d", source: "replicate.com" },
  { id: "x-6", company: "Tally", role: "Founding Designer", score: 84, verdict: "VERIFIED" as const, posted: "6d", source: "tally.so" },
  { id: "x-7", company: "Hello-Crypto Pro", role: "Treasury Coordinator", score: 21, verdict: "DECLINE" as const, posted: "12h", source: "recruiter dm" },
  { id: "x-8", company: "Arc Browser", role: "Product Designer", score: 58, verdict: "INVESTIGATE" as const, posted: "4w", source: "wellfound.com" },
];
